apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{ .Release.Name }}-bulker'
  labels:
    katenary.io/component: bulker
    katenary.io/project: '{{ .Chart.Name }}'
    katenary.io/release: '{{ .Release.Name }}'
  annotations:
    katenary.io/docker-compose-sha1: da39a3ee5e6b4b0d3255bfef95601890afd80709
    katenary.io/version: 2.0.0-beta2
spec:
  replicas: 1
  selector:
    matchLabels:
      katenary.io/component: bulker
      katenary.io/release: '{{ .Release.Name }}'
  template:
    metadata:
      labels:
        katenary.io/component: bulker
        katenary.io/release: '{{ .Release.Name }}'
    spec:
      initContainers:
        - name: check-redis
          image: busybox
          command:
            - sh
            - -c
            - |-
              OK=0
              echo "Checking redis port"
              while [ $OK != 1 ]; do
                  echo -n "."
                  nc -z {{ .Release.Name }}-redis {{ .Values.redis.service.port }} 2>&1 >/dev/null && OK=1 || sleep 1
              done
              echo
              echo "Done"
        - name: check-kafka
          image: busybox
          command:
            - sh
            - -c
            - |-
              OK=0
              echo "Checking kafka port"
              while [ $OK != 1 ]; do
                  echo -n "."
                  nc -z {{ .Release.Name }}-kafka {{ .Values.kafka.service.port }} 2>&1 >/dev/null && OK=1 || sleep 1
              done
              echo
              echo "Done"
      containers:
        - name: bulker
          image: '{{ .Values.bulker.repository.image }}{{ if ne .Values.bulker.repository.tag "" }}:{{ .Values.bulker.repository.tag }}{{ end }}'
          ports:
            - name: bulker
              containerPort: {{ .Values.bulker.environment.BULKER_HTTP_PORT }}
          env:
            - name: BULKER_CONFIG_SOURCE
              value: '{{ tpl .Values.bulker.environment.BULKER_CONFIG_SOURCE . }}'
            - name: BULKER_HTTP_PORT
              value: '{{ tpl .Values.bulker.environment.BULKER_HTTP_PORT . }}'
            - name: BULKER_KAFKA_BOOTSTRAP_SERVERS
              value: '{{ .Release.Name }}-kafka:{{ .Values.kafka.service.port }}'
            - name: BULKER_AUTH_TOKENS
              valueFrom:
                secretKeyRef:
                  key: BULKER_AUTH_TOKEN
                  name: '{{ tpl .Values.secrets.name . }}'
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  key: REDIS_URL
                  name: '{{ tpl .Values.secrets.name . }}'
          livenessProbe:
            exec:
              command:
                - curl
                - -f
                - 'http://localhost:{{ .Values.bulker.environment.BULKER_HTTP_PORT }}/ready'
            periodSeconds: 2
            initialDelaySeconds: 0
            successThreshold: 1
            failureThreshold: 15
          resources:
            requests:
              cpu: "100m"
              memory: "100M"

