apiVersion: v1
kind: Service
metadata:
  name: '{{ .Release.Name }}-bulker'
  labels:
    katenary.io/component: bulker
    katenary.io/project: '{{ .Chart.Name }}'
    katenary.io/release: '{{ .Release.Name }}'
  annotations:
    katenary.io/docker-compose-sha1: da39a3ee5e6b4b0d3255bfef95601890afd80709
    katenary.io/version: 2.0.0-beta2
spec:
  selector:
    katenary.io/component: bulker
    katenary.io/release: '{{ .Release.Name }}'
  ports:
    - protocol: TCP
      port: {{ .Values.bulker.environment.BULKER_HTTP_PORT }}
      targetPort: {{ .Values.bulker.environment.BULKER_HTTP_PORT }}
