---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: '{{ .Release.Name }}-console'
  labels:
    katenary.io/component: console
    katenary.io/project: '{{ .Chart.Name }}'
    katenary.io/release: '{{ .Release.Name }}'
  annotations:
    katenary.io/docker-compose-sha1: da39a3ee5e6b4b0d3255bfef95601890afd80709
    katenary.io/version: 2.0.0-beta2
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 20m
spec:
  tls:
  - secretName: '{{ .Release.Name}}-jitsu.graphext.com-tls'
    hosts:
    - {{ .Values.console.ingress.host }}
  rules:
  - host: {{ .Values.console.ingress.host }}
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: '{{ .Release.Name }}-console'
            port:
              number: {{ .Values.console.service.port }}