{{ if eq .Values.console.environment.SYNCS_ENABLED "true" }}
apiVersion: v1
kind: Service
metadata:
  name: '{{ .Release.Name }}-syncctl'
  labels:
    katenary.io/component: syncctl
    katenary.io/project: '{{ .Chart.Name }}'
    katenary.io/release: '{{ .Release.Name }}'
  annotations:
    katenary.io/docker-compose-sha1: da39a3ee5e6b4b0d3255bfef95601890afd80709
    katenary.io/version: 2.0.0-beta2
spec:
  selector:
    katenary.io/component: syncctl
    katenary.io/release: '{{ .Release.Name }}'
  ports:
    - protocol: TCP
      port: 3043
      targetPort: 3043
{{ end }}