---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: '{{ .Release.Name }}-syncctl-jobs-role'
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "create", "update", "patch", "delete"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: '{{ .Release.Name }}-syncctl-jobs-role-binding'
subjects:
- kind: ServiceAccount
  namespace: '{{ .Release.Namespace }}'
  name: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: '{{ .Release.Name }}-syncctl-jobs-role'