apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{ .Release.Name }}-zookeeper'
  labels:
    katenary.io/component: zookeeper
    katenary.io/project: '{{ .Chart.Name }}'
    katenary.io/release: '{{ .Release.Name }}'
  annotations:
    katenary.io/docker-compose-sha1: da39a3ee5e6b4b0d3255bfef95601890afd80709
    katenary.io/version: 2.0.0-beta2
spec:
  replicas: 1
  selector:
    matchLabels:
      katenary.io/component: zookeeper
      katenary.io/release: '{{ .Release.Name }}'
  template:
    metadata:
      labels:
        katenary.io/component: zookeeper
        katenary.io/release: '{{ .Release.Name }}'
    spec:
      containers:
        - name: zookeeper
          image: '{{ .Values.zookeeper.repository.image }}{{ if ne .Values.zookeeper.repository.tag "" }}:{{ .Values.zookeeper.repository.tag }}{{ end }}'
          ports:
            - name: zookeeper
              containerPort: {{ .Values.zookeeper.service.port }}
          resources:
            requests:
              cpu: "50m"
              memory: "300M"
